version: "3.8"

services:
  api-auth:
    build: .
    container_name: api-auth
    volumes:
      - .:/var/www
    networks:
      - backend-network
    expose:
      - "9000"

  nginx-auth:
    image: nginx:alpine
    container_name: nginx-auth
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api-auth
    networks:
      - backend-network

networks:
  backend-network:
    external: true
